// website/components/dashboard-section.tsx
import { motion } from "framer-motion";
import HeaderSection from "@/components/ui/header";
import React from "react";

interface DashboardData {
  dctPrice: number;
  providerCount: number;
  totalBlocks: number;
  blocksUntilHalving: number;
  validatorCount: number;
  blockReward: number;
}

interface DashboardSectionProps {
  dashboardData: DashboardData;
}

interface DashboardItem {
  title: string;
  key: keyof DashboardData;
  format: (value: number | undefined) => string;
  tooltip: string;
}

const dashboardItems: DashboardItem[] = [
  {
    title: "Latest DCT Price 💎",
    key: "dctPrice",
    format: (value: number | undefined) =>
      value ? `$${value.toFixed(4)}` : "$0.0000",
    tooltip:
      "Our token is like a digital diamond: rare, valuable, and utterly decent! Plus, the price updates live from KongSwap.io!",
  },
  {
    title: "Provider Squad 🤝",
    key: "providerCount",
    format: (value: number | undefined) =>
      value ? `${value} providers` : "0 providers",
    tooltip: "Our awesome providers making the cloud decent again!",
  },
  {
    title: "Block Party 🎉",
    key: "totalBlocks",
    format: (value: number | undefined) =>
      value ? value.toLocaleString() : "0",
    tooltip: "Blocks validated and counting!",
  },
  {
    title: "Blocks Until Next Halving ⏳",
    key: "blocksUntilHalving",
    format: (value: number | undefined) =>
      value ? value.toLocaleString() : "0",
    tooltip: "Blocks until rewards halve!",
  },
  {
    title: "Current Block Validators 🛡️",
    key: "validatorCount",
    format: (value: number | undefined) =>
      value ? `${value} validators` : "0 validators",
    tooltip: "Validators keeping us decent!",
  },
  {
    title: "Accumulated Block Rewards 🎁",
    key: "blockReward",
    format: (value: number | undefined) =>
      value ? `${value.toFixed(2)} DCT` : "0.00 DCT",
    tooltip: "DCT per validated block! With carry-over if unclaimed!",
  },
];

const DashboardSection: React.FC<DashboardSectionProps> = ({
  dashboardData,
}) => {
  return (
    <section id="dashboard">
      <HeaderSection
        title="Dashboard"
        subtitle="Get a quick overview of Decent Cloud's current stats."
      />
      <motion.div
        className="max-w-4xl mx-auto p-6 grid grid-cols-1 sm:grid-cols-2 gap-4"
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.4 }}
        transition={{ duration: 0.5 }}
      >
        {dashboardItems.map((item, index) => (
          <div
            key={index}
            className="border border-white/10 group relative flex flex-col bg-gradient-to-r from-gray-800/30 to-gray-700/30 rounded-xl p-3 sm:p-4 hover:bg-white/10 hover:shadow-xl transition duration-300 ease-in-out shadow-lg cursor-help"
          >
            <div className="font-semibold text-center text-white/90 text-lg sm:text-xl tracking-wide">
              {item.title}
            </div>
            <div className="text-blue-400 font-bold text-xl sm:text-2xl text-center mt-2">
              {item.format(dashboardData[item.key])}
            </div>

            {/* Tooltip */}
            <div
              className="absolute opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-gray-900 text-white text-xs rounded-lg p-3 shadow-xl border border-white/10
                 left-1/2 transform -translate-x-1/2 top-full mt-2 w-56 z-50 pointer-events-none"
            >
              {item.tooltip}
            </div>
          </div>
        ))}
      </motion.div>
    </section>
  );
};

export default DashboardSection;

// website-svelte/src/lib/components/DashboardSection.svelte
<script lang="ts">
	interface Props {
		dashboardData: {
			dctPrice: number;
			providerCount: number;
			totalBlocks: number;
			blocksUntilHalving: number;
			rewardPerBlock: number;
			accumulatedRewards: number;
		};
		error?: string | null;
	}

	let { dashboardData, error = null }: Props = $props();

	const stats = $derived([
		{
			label: "DCT Price",
			value: `$${dashboardData.dctPrice.toFixed(4)}`,
			icon: "💰",
		},
		{
			label: "Providers",
			value: dashboardData.providerCount.toString(),
			icon: "🖥️",
		},
		{
			label: "Total Blocks",
			value: dashboardData.totalBlocks.toLocaleString(),
			icon: "⛓️",
		},
		{
			label: "Blocks Until Halving",
			value: dashboardData.blocksUntilHalving.toLocaleString(),
			icon: "📉",
		},
		{
			label: "Validators",
			value: dashboardData.validatorCount.toString(),
			icon: "✅",
		},
		{
			label: "Reward Per Block",
			value: `${dashboardData.rewardPerBlock.toFixed(2)} DCT`,
			icon: "🎁",
		},
		{
			label: "Accumulated Rewards",
			value: `${dashboardData.accumulatedRewards.toFixed(2)} DCT`,
			icon: "💰",
		},
	]);
</script>

<section class="py-20 px-4">
	<div class="max-w-7xl mx-auto">
		<h2 class="text-4xl md:text-5xl font-bold text-center mb-4">
			Network Statistics
		</h2>
		<p class="text-xl text-white/70 text-center mb-16">
			Real-time data from the Decent Cloud network
		</p>

		{#if error}
			<div class="mb-8 bg-red-500/20 border border-red-500/30 rounded-lg p-4 text-red-400 text-center">
				<p class="font-semibold">Error loading statistics</p>
				<p class="text-sm mt-1">{error}</p>
			</div>
		{/if}

		<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-6">
			{#each stats as stat}
				<div
					class="bg-white/10 backdrop-blur-lg rounded-xl p-6 text-center hover:bg-white/20 transition-all"
				>
					<div class="text-4xl mb-2">{stat.icon}</div>
					<div class="text-2xl font-bold mb-1">{stat.value}</div>
					<div class="text-sm text-white/60">{stat.label}</div>
				</div>
			{/each}
		</div>

		<div class="mt-12 text-center">
			<a
				href="/dashboard"
				class="inline-block px-8 py-3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg font-semibold hover:from-blue-600 hover:to-purple-700 transition-all"
			>
				View Full Dashboard
			</a>
		</div>
	</div>
</section>
