// website/components/seed-phrase-dialog.tsx
"use client";

import * as Dialog from "@radix-ui/react-dialog";
import { Button } from "@/components/ui/button";
import { useEffect, useState } from "react";
import { generateNewSeedPhrase } from "@/lib/auth-context";
import { addSeedPhrase as persistSeedPhrase } from "@/lib/seed-storage";

interface SeedPhraseDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit?: (phrase: string) => void;
  withSeedPhrase?: string | null;
  mode?: 'backup' | 'login';
}

export function SeedPhraseDialog({
  isOpen,
  onClose,
  onSubmit,
  withSeedPhrase: withSeedPhrase = null,
  mode = 'login'
}: SeedPhraseDialogProps) {
  const [seedPhrase, setSeedPhrase] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      setSeedPhrase("");
      setError("");
      setIsGenerating(false);
    } else if (withSeedPhrase && mode === 'backup') {
      setSeedPhrase(withSeedPhrase);
      setIsGenerating(false);
    }
  }, [isOpen, withSeedPhrase, mode]);

  const handleGenerateNew = () => {
    const newPhrase = generateNewSeedPhrase();
    setSeedPhrase(newPhrase);
    setIsGenerating(true);
    setError("");
  };

  const handleConfirm = () => {
    const trimmedSeedPhrase = seedPhrase.trim();
    console.info("Confirming seed phrase:", trimmedSeedPhrase);
    if (!trimmedSeedPhrase) {
      setError("Please enter your seed phrase");
      return;
    }

    // Basic validation - check if it's a valid mnemonic (12 or 24 words)
    const wordCount = trimmedSeedPhrase.split(/\s+/).length;
    if (wordCount !== 12 && wordCount !== 24) {
      setError("Invalid seed phrase. Must be 12 or 24 words");
      return;
    }

    try {
      // Store seed phrase in the seed_phrases array
      persistSeedPhrase(trimmedSeedPhrase);

      onSubmit?.(trimmedSeedPhrase);
      onClose();
    } catch (err) {
      setError(`Invalid seed phrase format: ${err}`);
    }
  };

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setSeedPhrase(e.target.value);
    setError("");
    setIsGenerating(false);
  };

  return (
    <Dialog.Root open={isOpen} onOpenChange={onClose}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50" />
        <Dialog.Content
          className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 bg-white rounded-lg p-4 sm:p-6 shadow-xl w-[95vw] sm:w-[90vw] max-w-md z-50"
          aria-describedby="dialog-description"
        >
          <Dialog.Title className="text-lg sm:text-xl font-semibold mb-3 sm:mb-4 text-gray-800">
            {mode === 'backup' ? 'Your Backup Seed Phrase' : 'Seed Phrase Authentication (Login/Register)'}
          </Dialog.Title>

          <div id="dialog-description" className="space-y-3 sm:space-y-4">
            {mode === 'login' && (
              <div className="flex gap-2 sm:gap-4 mb-4 sm:mb-6">
                <Button
                  onClick={handleGenerateNew}
                  className="flex-1 bg-blue-500 text-white hover:bg-blue-600 h-12 sm:h-10 text-sm sm:text-base"
                >
                  Generate New
                </Button>
                <Button
                  onClick={() => {
                    setSeedPhrase("");
                    setIsGenerating(false);
                  }}
                  className="flex-1 bg-gray-400 text-white hover:bg-gray-600 h-12 sm:h-10 text-sm sm:text-base"
                  disabled={!isGenerating}
                >
                  Enter Existing
                </Button>
              </div>
            )}

            {mode === 'backup' || isGenerating ? (
              <>
                <p className="text-sm sm:text-base text-gray-600">
                  {mode === 'backup' 
                    ? "This is your seed phrase for this identity. Store it safely to recover your account if needed." 
                    : "This is your new seed phrase. Write it down and keep it safe. You'll need it to recover your account."}
                </p>

                <div className="bg-gray-50 p-3 sm:p-4 rounded break-all">
                  <p className="font-mono text-sm sm:text-base text-gray-800">
                    {seedPhrase}
                  </p>
                </div>

                <div className="bg-red-50 p-3 sm:p-4 rounded border-2 border-red-500">
                  <p className="text-xs sm:text-sm">
                    <span className="font-bold text-red-600">
                      ⚠️ WARNING! ⚠️ If you lose this seed phrase, you will{" "}
                      <span className="underline">PERMANENTLY LOSE ACCESS</span>{" "}
                      to your account and all associated funds. This is your{" "}
                      <span className="underline">ONLY</span> recovery key.
                      Write it down and keep it safe! 🔒
                    </span>
                  </p>
                </div>
              </>
            ) : (
              <p className="text-sm sm:text-base text-gray-600">
                Enter an existing seed phrase to access your account. Using the
                same seed phrase as in the CLI will give you the same identity
                across both platforms.
              </p>
            )}

            {!isGenerating && mode === 'login' && (
              <textarea
                value={seedPhrase}
                onChange={handleInput}
                className="w-full h-28 sm:h-32 p-3 sm:p-4 border rounded font-mono text-sm sm:text-base text-gray-800 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50"
                placeholder="Enter your 12 or 24 word seed phrase..."
              />
            )}

            {error && (
              <p className="text-xs sm:text-sm text-red-600">{error}</p>
            )}

            <Button
              onClick={mode === 'backup' ? onClose : handleConfirm}
              className="w-full bg-emerald-500 text-white hover:bg-emerald-600 h-14 sm:h-12 text-sm sm:text-base"
              disabled={mode === 'login' && !seedPhrase.trim()}
            >
              {mode === 'backup'
                ? "I have Safely Stored My Recovery Phrase"
                : isGenerating
                ? "I have Saved My Seed Phrase"
                : "Login/Register with Seed Phrase"}
            </Button>
          </div>

          <Dialog.Close asChild>
            <button
              className="absolute top-3 sm:top-4 right-3 sm:right-4 p-2 rounded-full text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-all duration-200 touch-manipulation"
              aria-label="Close"
            >
              <svg
                className="w-6 h-6 sm:w-5 sm:h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

// website-svelte/src/lib/components/SeedPhraseDialog.svelte
<script lang="ts">
	import { generateMnemonic, validateMnemonic } from 'bip39';

	let { open = $bindable(false), onConfirm } = $props<{
		open: boolean;
		onConfirm: (seedPhrase: string) => void;
	}>();

	let seedPhrase = $state('');
	let error = $state('');
	let mode = $state<'choice' | 'generate' | 'import'>('choice');

	const buttonBaseClass = 'flex-1 px-6 py-3 rounded-lg text-white transition-colors';
	const buttonSecondaryClass = `${buttonBaseClass} bg-white/10 border border-white/20 hover:bg-white/20`;
	const buttonPrimaryClass = (gradient: string) =>
		`${buttonBaseClass} bg-gradient-to-r ${gradient} font-semibold hover:brightness-110 transition-all`;

	function resetState() {
		mode = 'choice';
		seedPhrase = '';
		error = '';
	}

	function handleGenerateNew() {
		seedPhrase = generateMnemonic();
		mode = 'generate';
		error = '';
	}

	function handleImportExisting() {
		seedPhrase = '';
		mode = 'import';
		error = '';
	}

	function handleBack() {
		resetState();
	}

	function handleConfirm() {
		const trimmed = seedPhrase.trim();
		if (!trimmed) {
			error = 'Please enter your seed phrase';
			return;
		}

		if (!validateMnemonic(trimmed)) {
			error = 'Invalid seed phrase. Must be a valid 12 or 24-word mnemonic';
			return;
		}

		try {
			onConfirm(trimmed);
			handleClose();
		} catch (err) {
			error = `Invalid seed phrase: ${err instanceof Error ? err.message : String(err)}`;
		}
	}

	function handleClose() {
		if (open) {
			open = false;
			resetState();
		}
	}
</script>

{#if open}
	<div
		class="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
		onclick={handleClose}
		onkeydown={(e) => e.key === 'Escape' && handleClose()}
		role="button"
		tabindex="0"
	>
		<div
			class="bg-gray-900 rounded-2xl p-8 max-w-2xl w-full border border-white/20 shadow-2xl"
			onclick={(e) => e.stopPropagation()}
			onkeydown={(e) => e.stopPropagation()}
			role="dialog"
			tabindex="-1"
		>
			{#if mode === 'choice'}
				<h2 class="text-3xl font-bold text-white mb-2">Seed Phrase Authentication</h2>
				<p class="text-white/60 mb-8">Choose how you want to proceed</p>
				<div class="space-y-4">
					<button
						type="button"
						onclick={handleGenerateNew}
						class="w-full p-6 bg-gradient-to-r from-blue-500/20 to-purple-600/20 border border-blue-500/30 rounded-xl hover:border-blue-400 transition-all group text-left"
					>
						<div class="flex items-center gap-4">
							<span class="text-4xl">✨</span>
							<div class="flex-1">
								<h3 class="text-white font-semibold text-lg group-hover:text-blue-400">
									Generate New Seed Phrase
								</h3>
								<p class="text-white/60 text-sm mt-1">Create a new identity with a fresh 12-word recovery phrase</p>
							</div>
							<span class="text-white/40 text-2xl">→</span>
						</div>
					</button>
					<button
						type="button"
						onclick={handleImportExisting}
						class="w-full p-6 bg-gradient-to-r from-purple-500/20 to-pink-600/20 border border-purple-500/30 rounded-xl hover:border-purple-400 transition-all group text-left"
					>
						<div class="flex items-center gap-4">
							<span class="text-4xl">🔑</span>
							<div class="flex-1">
								<h3 class="text-white font-semibold text-lg group-hover:text-purple-400">
									Import Existing Seed Phrase
								</h3>
								<p class="text-white/60 text-sm mt-1">Use your existing 12 or 24-word recovery phrase</p>
							</div>
							<span class="text-white/40 text-2xl">→</span>
						</div>
					</button>
				</div>
			{:else if mode === 'generate'}
				<h2 class="text-3xl font-bold text-white mb-2">Your New Seed Phrase</h2>
				<p class="text-white/60 mb-6">
					<strong class="text-yellow-400">⚠️ IMPORTANT:</strong> Write down these words and store them safely. This is the ONLY way to recover your account.
				</p>
				<div class="bg-gray-800 border border-white/20 rounded-xl p-6 mb-6">
					<div class="grid grid-cols-3 gap-4">
						{#each seedPhrase.split(' ') as word, i}
							<div class="flex items-center gap-2 text-white">
								<span class="text-white/40 text-sm w-6">{i + 1}.</span>
								<span class="font-mono font-semibold">{word}</span>
							</div>
						{/each}
					</div>
				</div>
				<div class="bg-red-900/20 border border-red-500/30 rounded-lg p-4 mb-6">
					<p class="text-red-400 text-sm">
						<strong>Never share your seed phrase with anyone!</strong> Anyone with access to these words can control your account and funds. There is NO way to recover a lost seed phrase.
					</p>
				</div>
				<div class="flex gap-4">
					<button type="button" onclick={handleBack} class={buttonSecondaryClass}>Back</button>
					<button type="button" onclick={handleConfirm} class={buttonPrimaryClass('from-blue-500 to-purple-600')}>
						I've Saved It, Continue
					</button>
				</div>
			{:else if mode === 'import'}
				<h2 class="text-3xl font-bold text-white mb-2">Import Seed Phrase</h2>
				<p class="text-white/60 mb-6">Enter your 12 or 24-word recovery phrase</p>
				{#if error}
					<div class="mb-4 p-4 bg-red-500/20 border border-red-500/30 rounded-lg text-red-400 text-sm">{error}</div>
				{/if}
				<textarea
					bind:value={seedPhrase}
					placeholder="word1 word2 word3 ..."
					class="w-full h-32 px-4 py-3 bg-gray-800 border border-white/20 rounded-lg text-white font-mono text-sm focus:outline-none focus:border-purple-500 resize-none mb-6"
					oninput={() => (error = '')}
				></textarea>
				<div class="bg-blue-900/20 border border-blue-500/30 rounded-lg p-4 mb-6">
					<p class="text-blue-400 text-sm">💡 Tip: Paste your seed phrase directly. Words should be separated by spaces.</p>
				</div>
				<div class="flex gap-4">
					<button type="button" onclick={handleBack} class={buttonSecondaryClass}>Back</button>
					<button type="button" onclick={handleConfirm} class={buttonPrimaryClass('from-purple-500 to-pink-600')}>
						Import & Continue
					</button>
				</div>
			{/if}

			<button
				type="button"
				onclick={handleClose}
				class="w-full mt-6 px-4 py-3 text-white/60 hover:text-white transition-colors"
			>
				Cancel
			</button>
		</div>
	</div>
{/if}
