// website/app/dashboard/offerings/page.tsx
"use client";

import { useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus, faEdit, faTrash } from "@fortawesome/free-solid-svg-icons";
import HeaderSection from "@/components/ui/header";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

// Mock data for demonstration purposes
const mockOfferings = [
  {
    id: "1",
    name: "High Performance Computing Node",
    type: "Compute",
    price: "0.05 DCT/hour",
    specs: "8 vCPUs, 16GB RAM, 100GB SSD",
    location: "Europe",
    status: "Active",
    created: "2025-01-15",
  },
  {
    id: "2",
    name: "Storage Solution",
    type: "Storage",
    price: "0.02 DCT/GB/month",
    specs: "Redundant storage, 99.9% uptime",
    location: "North America",
    status: "Active",
    created: "2025-01-20",
  },
];

export default function OfferingsPage() {
  const [offerings, setOfferings] = useState(mockOfferings);

  const handleDeleteOffering = (id: string) => {
    setOfferings(offerings.filter((offering) => offering.id !== id));
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <HeaderSection
        title="My Offerings"
        subtitle="Manage your cloud offerings on the Decent Cloud marketplace"
      />

      <div className="bg-white/10 p-6 rounded-lg backdrop-blur-sm mb-6">
        <div className="mb-6">
          <h3 className="text-xl font-semibold mb-2 text-white">
            Provider Dashboard
          </h3>
          <p className="text-white/90 mb-4">
            Add, edit, and manage your cloud offerings on the Decent Cloud
            marketplace.
          </p>
          <div className="bg-blue-900/30 p-4 rounded-lg mb-4">
            <p className="text-yellow-300 font-medium mb-2">⚠️ Example Data</p>
            <p className="text-white/90 text-sm">
              This is a demonstration page with mock data. In the future,
              providers will be able to add real offerings to the marketplace.
            </p>
          </div>
        </div>

        <div className="flex justify-end mb-6">
          <Button className="bg-green-600 hover:bg-green-700 text-white flex items-center gap-2">
            <FontAwesomeIcon icon={faPlus} />
            <span>Add New Offering</span>
          </Button>
        </div>
      </div>

      <Card className="p-6 bg-white/10 backdrop-blur-sm rounded-lg border border-white/20">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-xl font-semibold text-white">
            Your Current Offerings
          </h3>
          <div className="text-xs text-white/70 bg-blue-500/20 px-3 py-1 rounded-full">
            {offerings.length} offerings
          </div>
        </div>

        {offerings.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full text-white">
              <thead>
                <tr className="border-b border-white/20">
                  <th className="py-3 px-4 text-left">Name</th>
                  <th className="py-3 px-4 text-left">Type</th>
                  <th className="py-3 px-4 text-left">Price</th>
                  <th className="py-3 px-4 text-left">Location</th>
                  <th className="py-3 px-4 text-left">Status</th>
                  <th className="py-3 px-4 text-left">Actions</th>
                </tr>
              </thead>
              <tbody>
                {offerings.map((offering) => (
                  <tr
                    key={offering.id}
                    className="border-b border-white/10 hover:bg-white/5"
                  >
                    <td className="py-3 px-4">{offering.name}</td>
                    <td className="py-3 px-4">{offering.type}</td>
                    <td className="py-3 px-4 text-blue-400">
                      {offering.price}
                    </td>
                    <td className="py-3 px-4">{offering.location}</td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-1 rounded-full text-xs bg-green-500/20 text-green-400">
                        {offering.status}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex space-x-2">
                        <button
                          className="p-1.5 rounded bg-blue-500/20 text-blue-400 hover:bg-blue-500/40 transition-colors"
                          title="Edit offering"
                        >
                          <FontAwesomeIcon icon={faEdit} />
                        </button>
                        <button
                          className="p-1.5 rounded bg-red-500/20 text-red-400 hover:bg-red-500/40 transition-colors"
                          title="Delete offering"
                          onClick={() => handleDeleteOffering(offering.id)}
                        >
                          <FontAwesomeIcon icon={faTrash} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="text-center py-8 text-white/70">
            <p>You haven't added any offerings yet.</p>
            <Button className="mt-4 bg-blue-600 hover:bg-blue-700 text-white">
              Add Your First Offering
            </Button>
          </div>
        )}
      </Card>
    </div>
  );
}

// website-svelte/src/routes/dashboard/offerings/+page.svelte
<script lang="ts">
	// TODO: Integrate with actual offerings API when available
	interface Offering {
		id: string;
		name: string;
		type: 'VM' | 'Storage' | 'Network';
		status: 'active' | 'paused' | 'pending';
		price: number;
		revenue: number;
		activeUsers: number;
	}

	const mockOfferings: Offering[] = [
		{
			id: '1',
			name: 'Cloud VM Standard',
			type: 'VM',
			status: 'active',
			price: 0.05,
			revenue: 125.5,
			activeUsers: 3
		},
		{
			id: '2',
			name: 'Object Storage',
			type: 'Storage',
			status: 'active',
			price: 0.02,
			revenue: 45.25,
			activeUsers: 5
		},
		{
			id: '3',
			name: 'CDN Edge Node',
			type: 'Network',
			status: 'paused',
			price: 0.08,
			revenue: 0,
			activeUsers: 0
		}
	];

	function getStatusColor(status: string) {
		switch (status) {
			case 'active':
				return 'bg-green-500/20 text-green-400 border-green-500/30';
			case 'paused':
				return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30';
			case 'pending':
				return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
			default:
				return 'bg-gray-500/20 text-gray-400 border-gray-500/30';
		}
	}

	function getTypeIcon(type: string) {
		switch (type) {
			case 'VM':
				return '💻';
			case 'Storage':
				return '💾';
			case 'Network':
				return '🌐';
			default:
				return '📦';
		}
	}
</script>

<div class="space-y-8">
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-4xl font-bold text-white mb-2">My Offerings</h1>
			<p class="text-white/60">Manage your cloud service offerings</p>
		</div>
		<button
			class="px-6 py-3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg font-semibold hover:brightness-110 hover:scale-105 transition-all"
		>
			+ Create Offering
		</button>
	</div>

	<!-- Stats Summary -->
	<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
		<div class="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
			<div class="flex items-center justify-between mb-2">
				<h3 class="text-white/70 text-sm font-medium">Active Offerings</h3>
				<span class="text-2xl">📦</span>
			</div>
			<p class="text-3xl font-bold text-white">
				{mockOfferings.filter((o) => o.status === 'active').length}
			</p>
		</div>

		<div class="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
			<div class="flex items-center justify-between mb-2">
				<h3 class="text-white/70 text-sm font-medium">Total Revenue</h3>
				<span class="text-2xl">💰</span>
			</div>
			<p class="text-3xl font-bold text-white">
				{mockOfferings.reduce((sum, o) => sum + o.revenue, 0).toFixed(2)} DCT
			</p>
		</div>

		<div class="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20">
			<div class="flex items-center justify-between mb-2">
				<h3 class="text-white/70 text-sm font-medium">Active Users</h3>
				<span class="text-2xl">👥</span>
			</div>
			<p class="text-3xl font-bold text-white">
				{mockOfferings.reduce((sum, o) => sum + o.activeUsers, 0)}
			</p>
		</div>
	</div>

	<!-- Offerings Grid -->
	<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
		{#each mockOfferings as offering}
			<div
				class="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20 hover:border-white/40 transition-all group"
			>
				<div class="flex items-start justify-between mb-4">
					<span class="text-4xl">{getTypeIcon(offering.type)}</span>
					<span
						class="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-medium border {getStatusColor(
							offering.status
						)}"
					>
						<span class="w-2 h-2 rounded-full bg-current"></span>
						{offering.status}
					</span>
				</div>

				<h3 class="text-xl font-bold text-white mb-2 group-hover:text-blue-400 transition-colors">
					{offering.name}
				</h3>

				<div class="space-y-2 text-sm">
					<div class="flex items-center justify-between text-white/70">
						<span>Type</span>
						<span class="text-white font-medium">{offering.type}</span>
					</div>
					<div class="flex items-center justify-between text-white/70">
						<span>Price</span>
						<span class="text-white font-medium">{offering.price} DCT/hr</span>
					</div>
					<div class="flex items-center justify-between text-white/70">
						<span>Revenue</span>
						<span class="text-white font-medium">{offering.revenue.toFixed(2)} DCT</span>
					</div>
					<div class="flex items-center justify-between text-white/70">
						<span>Active Users</span>
						<span class="text-white font-medium">{offering.activeUsers}</span>
					</div>
				</div>

				<div class="mt-4 pt-4 border-t border-white/10 flex gap-2">
					<button
						class="flex-1 px-4 py-2 bg-white/10 rounded-lg text-sm font-medium hover:bg-white/20 transition-all"
					>
						Edit
					</button>
					<button
						class="flex-1 px-4 py-2 bg-white/10 rounded-lg text-sm font-medium hover:bg-white/20 transition-all"
					>
						{offering.status === 'active' ? 'Pause' : 'Activate'}
					</button>
				</div>
			</div>
		{/each}
	</div>

	<!-- Empty State (if no offerings) -->
	{#if mockOfferings.length === 0}
		<div class="text-center py-16">
			<span class="text-6xl mb-4 block">📦</span>
			<h3 class="text-2xl font-bold text-white mb-2">No Offerings Yet</h3>
			<p class="text-white/60 mb-6">Create your first cloud service offering to get started</p>
			<button
				class="px-6 py-3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg font-semibold hover:brightness-110 hover:scale-105 transition-all"
			>
				Create Your First Offering
			</button>
		</div>
	{/if}
</div>
