// website-svelte/src/routes/dashboard/marketplace/+page.svelte
<script lang="ts">
	// TODO: Integrate with actual marketplace API when available
	interface MarketplaceOffering {
		id: string;
		provider: string;
		name: string;
		type: 'VM' | 'Storage' | 'Network';
		price: number;
		rating: number;
		available: boolean;
		specs: string;
	}

	const mockMarketplace: MarketplaceOffering[] = [
		{
			id: '1',
			provider: 'Provider Alpha',
			name: 'High Performance VM',
			type: 'VM',
			price: 0.08,
			rating: 4.8,
			available: true,
			specs: '8 vCPU, 16GB RAM, 200GB SSD'
		},
		{
			id: '2',
			provider: 'Provider Beta',
			name: 'Object Storage Pro',
			type: 'Storage',
			price: 0.03,
			rating: 4.9,
			available: true,
			specs: '1TB storage, 99.9% uptime'
		},
		{
			id: '3',
			provider: 'Provider Gamma',
			name: 'CDN Edge Network',
			type: 'Network',
			price: 0.12,
			rating: 4.7,
			available: true,
			specs: 'Global CDN, DDoS protection'
		},
		{
			id: '4',
			provider: 'Provider Delta',
			name: 'Budget VM',
			type: 'VM',
			price: 0.02,
			rating: 4.5,
			available: true,
			specs: '2 vCPU, 4GB RAM, 50GB SSD'
		},
		{
			id: '5',
			provider: 'Provider Epsilon',
			name: 'Archive Storage',
			type: 'Storage',
			price: 0.01,
			rating: 4.6,
			available: false,
			specs: 'Cold storage, unlimited'
		}
	];

	let searchQuery = '';
	let selectedType: 'all' | 'VM' | 'Storage' | 'Network' = 'all';

	$: filteredOfferings = mockMarketplace.filter((offering) => {
		const matchesSearch =
			offering.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
			offering.provider.toLowerCase().includes(searchQuery.toLowerCase());
		const matchesType = selectedType === 'all' || offering.type === selectedType;
		return matchesSearch && matchesType;
	});

	function getTypeIcon(type: string) {
		switch (type) {
			case 'VM':
				return '💻';
			case 'Storage':
				return '💾';
			case 'Network':
				return '🌐';
			default:
				return '📦';
		}
	}
</script>

<div class="space-y-8">
	<div>
		<h1 class="text-4xl font-bold text-white mb-2">Marketplace</h1>
		<p class="text-white/60">Discover and purchase cloud services from trusted providers</p>
	</div>

	<!-- Search and Filters -->
	<div class="flex flex-col md:flex-row gap-4">
		<div class="flex-1">
			<input
				type="text"
				placeholder="Search offerings..."
				bind:value={searchQuery}
				class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-white/50 focus:outline-none focus:border-blue-400 transition-colors"
			/>
		</div>
		<div class="flex gap-2">
			<button
				on:click={() => (selectedType = 'all')}
				class="px-4 py-3 rounded-lg font-medium transition-all {selectedType === 'all'
					? 'bg-blue-600 text-white'
					: 'bg-white/10 text-white/70 hover:bg-white/20'}"
			>
				All
			</button>
			<button
				on:click={() => (selectedType = 'VM')}
				class="px-4 py-3 rounded-lg font-medium transition-all {selectedType === 'VM'
					? 'bg-blue-600 text-white'
					: 'bg-white/10 text-white/70 hover:bg-white/20'}"
			>
				💻 VM
			</button>
			<button
				on:click={() => (selectedType = 'Storage')}
				class="px-4 py-3 rounded-lg font-medium transition-all {selectedType === 'Storage'
					? 'bg-blue-600 text-white'
					: 'bg-white/10 text-white/70 hover:bg-white/20'}"
			>
				💾 Storage
			</button>
			<button
				on:click={() => (selectedType = 'Network')}
				class="px-4 py-3 rounded-lg font-medium transition-all {selectedType === 'Network'
					? 'bg-blue-600 text-white'
					: 'bg-white/10 text-white/70 hover:bg-white/20'}"
			>
				🌐 Network
			</button>
		</div>
	</div>

	<!-- Results Count -->
	<div class="text-white/60">
		Showing {filteredOfferings.length} of {mockMarketplace.length} offerings
	</div>

	<!-- Marketplace Grid -->
	<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
		{#each filteredOfferings as offering}
			<div
				class="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20 hover:border-blue-400 transition-all group"
			>
				<div class="flex items-start justify-between mb-4">
					<span class="text-4xl">{getTypeIcon(offering.type)}</span>
					{#if offering.available}
						<span
							class="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-medium bg-green-500/20 text-green-400 border border-green-500/30"
						>
							<span class="w-2 h-2 rounded-full bg-current"></span>
							Available
						</span>
					{:else}
						<span
							class="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-medium bg-gray-500/20 text-gray-400 border border-gray-500/30"
						>
							Unavailable
						</span>
					{/if}
				</div>

				<h3 class="text-xl font-bold text-white mb-1 group-hover:text-blue-400 transition-colors">
					{offering.name}
				</h3>
				<p class="text-white/60 text-sm mb-4">{offering.provider}</p>

				<div class="space-y-2 text-sm mb-4">
					<div class="flex items-center justify-between text-white/70">
						<span>Type</span>
						<span class="text-white font-medium">{offering.type}</span>
					</div>
					<div class="flex items-center justify-between text-white/70">
						<span>Price</span>
						<span class="text-white font-medium">{offering.price} DCT/hr</span>
					</div>
					<div class="flex items-center justify-between text-white/70">
						<span>Rating</span>
						<span class="text-white font-medium flex items-center gap-1">
							⭐ {offering.rating}
						</span>
					</div>
				</div>

				<div class="text-white/60 text-sm mb-4 p-3 bg-white/5 rounded-lg">
					{offering.specs}
				</div>

				<button
					disabled={!offering.available}
					class="w-full px-4 py-3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg font-semibold hover:brightness-110 hover:scale-105 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
				>
					{offering.available ? 'Deploy Now' : 'Not Available'}
				</button>
			</div>
		{/each}
	</div>

	<!-- Empty State -->
	{#if filteredOfferings.length === 0}
		<div class="text-center py-16">
			<span class="text-6xl mb-4 block">🔍</span>
			<h3 class="text-2xl font-bold text-white mb-2">No Results Found</h3>
			<p class="text-white/60">Try adjusting your search or filters</p>
		</div>
	{/if}
</div>

// website/app/dashboard/marketplace/page.tsx
"use client";

import { useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSearch } from "@fortawesome/free-solid-svg-icons";
import HeaderSection from "@/components/ui/header";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

// Mock data for demonstration purposes
const mockOfferings = [
  {
    id: "1",
    name: "High Performance Computing Node",
    provider: "CloudNode Provider",
    price: "0.05 DCT/hour",
    specs: "8 vCPUs, 16GB RAM, 100GB SSD",
    location: "Europe",
    rating: 4.8,
  },
  {
    id: "2",
    name: "Storage Solution",
    provider: "DecentStore",
    price: "0.02 DCT/GB/month",
    specs: "Redundant storage, 99.9% uptime",
    location: "North America",
    rating: 4.6,
  },
  {
    id: "3",
    name: "Web Hosting",
    provider: "DecentralHost",
    price: "10 DCT/month",
    specs: "Unlimited bandwidth, 10GB storage",
    location: "Asia",
    rating: 4.7,
  },
  {
    id: "4",
    name: "AI Compute Cluster",
    provider: "NeuralNode",
    price: "0.1 DCT/hour",
    specs: "4 GPUs, 64GB RAM, optimized for ML",
    location: "Global",
    rating: 4.9,
  },
];

export default function MarketplacePage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [filteredOfferings, setFilteredOfferings] = useState(mockOfferings);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    const filtered = mockOfferings.filter(
      (offering) =>
        offering.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        offering.provider.toLowerCase().includes(searchTerm.toLowerCase()) ||
        offering.specs.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredOfferings(filtered);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <HeaderSection
        title="Marketplace"
        subtitle="Search for available cloud offerings from decentralized providers"
      />

      <div className="bg-white/10 p-6 rounded-lg backdrop-blur-sm mb-6">
        <div className="mb-6">
          <h3 className="text-xl font-semibold mb-2 text-white">
            Find Cloud Resources
          </h3>
          <p className="text-white/90 mb-4">
            Browse through available offerings from decentralized providers on
            the Decent Cloud network.
          </p>
          <div className="bg-blue-900/30 p-4 rounded-lg mb-4">
            <p className="text-yellow-300 font-medium mb-2">⚠️ Example Data</p>
            <p className="text-white/90 text-sm">
              This is a demonstration page with mock data. In the future, this
              marketplace will contain real offerings from providers on the
              network.
            </p>
          </div>
        </div>

        <form onSubmit={handleSearch} className="mb-6">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-grow relative">
              <input
                type="text"
                placeholder="Search by name, provider, or specifications..."
                className="w-full p-3 bg-white/20 border border-white/10 rounded-lg text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
              <FontAwesomeIcon
                icon={faSearch}
                className="absolute right-3 top-1/2 transform -translate-y-1/2 text-white/50"
              />
            </div>
            <Button
              type="submit"
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              Search
            </Button>
          </div>
        </form>
      </div>

      <Card className="p-6 bg-white/10 backdrop-blur-sm rounded-lg border border-white/20">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-xl font-semibold text-white">
            Available Offerings
          </h3>
          <div className="text-xs text-white/70 bg-blue-500/20 px-3 py-1 rounded-full">
            {filteredOfferings.length} results
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredOfferings.map((offering) => (
            <div
              key={offering.id}
              className="border border-white/10 rounded-lg p-4 bg-white/5 hover:bg-white/10 transition-colors"
            >
              <h4 className="text-lg font-medium text-white mb-2">
                {offering.name}
              </h4>
              <div className="flex justify-between mb-2">
                <span className="text-white/70 text-sm">Provider:</span>
                <span className="text-white font-medium">
                  {offering.provider}
                </span>
              </div>
              <div className="flex justify-between mb-2">
                <span className="text-white/70 text-sm">Price:</span>
                <span className="text-blue-400 font-medium">
                  {offering.price}
                </span>
              </div>
              <div className="flex justify-between mb-2">
                <span className="text-white/70 text-sm">Specs:</span>
                <span className="text-white">{offering.specs}</span>
              </div>
              <div className="flex justify-between mb-2">
                <span className="text-white/70 text-sm">Location:</span>
                <span className="text-white">{offering.location}</span>
              </div>
              <div className="flex justify-between mb-4">
                <span className="text-white/70 text-sm">Rating:</span>
                <span className="text-yellow-400">
                  {"★".repeat(Math.floor(offering.rating))} {offering.rating}
                </span>
              </div>
              <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white">
                View Details
              </Button>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
